require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
-- require "user.dap"
require "user.dap-swift"
-- require "user.dap-cpp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
-- require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.sant_autorun"
require "user.luasnips"
require "user.generic_autorun"
require "user.ts_autorun"

